### ISSUE TITLE
how to use it?

### ISSUE THREAD

**Issue by indigitale** [hiqdev/yii2-asset-col-resizable#1]
thanks but... how to use it?

**Comment by SilverFire** [comment]
Hello. This package provides asset-bundle for Yii2 and wraps [alvaro-prieto/colResizable](https://github.com/alvaro-prieto/colResizable) jQuery plugin.

Register the asset bundle (`\hiqdev\yii2\assets\colResizable::register($this)` in view) and follow the [manual for col-resizable](http://www.bacubacu.com/colresizable/) plugin

**Comment by indigitale** [comment]
I receive "Class 'hiqdev\yii2\assets\colResizable' not found"

**Comment by SilverFire** [comment]
Sorry, typo

`\hiqdev\yii2\assets\colResizable\ColResizableAsset::register($this)`
